# Cubist

In [2]:
import pandas as pd
import io
import sys
PATH = '/home/Elian,john y hector/Data'
DIR_DATA = '../Data/'
sys.path.append(PATH) if PATH not in list(sys.path) else None
import os
filename = DIR_DATA + 'heart.csv'

In [3]:
df=pd.read_csv(filename,',')
df.head(10)

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3441: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  exec(code_obj, self.user_global_ns, self.user_ns)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   
5   57    1   0       140   192    0        1      148      0      0.4      1   
6   56    0   1       140   294    0        0      153      0      1.3      1   
7   44    1   1       120   263    0        1      173      0      0.0      2   
8   52    1   2       172   199    1        1      162      0      0.5      2   
9   57    1   2       150   168    0        1      174      0      1.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1  
5   0     1       1  
6   0     2       1  
7   0     3       1  
8   0     3       1  
9   0     2       1

In [4]:
from cubist import Cubist
from sklearn.model_selection import train_test_split
from mlxtend.data import iris_data

x, y = iris_data()
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [5]:
#creación del modelo
model = Cubist() 
#entrenamiento del modelo
model.fit(x_train, y_train)
#predicciones
y_predict=model.predict(x_test)

/home/student10/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but Cubist was fitted with feature names
  warnings.warn(


In [6]:
for x in range(len(y_predict)):
    y_predict[x]=round(y_predict[x],0)

In [7]:
y_predict

array([1., 2., 2., 2., 0., 1., 2., 1., 2., 2., 0., 1., 0., 0., 0., 0., 1.,
       2., 2., 0., 0., 2., 1., 0., 1., 2., 1., 2., 2., 2., 2., 0., 2., 1.,
       1., 0., 2., 1.])

In [8]:
y_test

array([1, 2, 1, 2, 0, 1, 2, 1, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 1, 0, 0, 2,
       1, 0, 2, 2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 2, 1])

In [9]:
from sklearn.metrics import accuracy_score
#puntaje 
accuracy_score(y_test, y_predict)

0.8947368421052632

# ONER

In [10]:
from mlxtend.data import iris_data


X, y = iris_data()
dft=pd.DataFrame(X)
dft.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [11]:
import numpy as np


def get_feature_quartiles(X):
    X_discretized = X.copy()
    for col in range(X.shape[1]):
        for q, class_label in zip([1.0, 0.75, 0.5, 0.25], [3, 2, 1, 0]):
            threshold = np.quantile(X[:, col], q=q)
            X_discretized[X[:, col] <= threshold, col] = class_label
    return X_discretized.astype(np.int)

Xd = get_feature_quartiles(X)
Xd[:15]

<ipython-input-11-299126cba650>:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  return X_discretized.astype(np.int)


array([[0, 3, 0, 0],
       [0, 1, 0, 0],
       [0, 2, 0, 0],
       [0, 2, 0, 0],
       [0, 3, 0, 0],
       [1, 3, 1, 1],
       [0, 3, 0, 0],
       [0, 3, 0, 0],
       [0, 1, 0, 0],
       [0, 2, 0, 0],
       [1, 3, 0, 0],
       [0, 3, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 3, 0, 0]])

In [12]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(Xd, y, random_state=0, stratify=y)

In [13]:
from mlxtend.classifier import OneRClassifier
oner = OneRClassifier()

oner.fit(X_train, y_train);

In [14]:
oner.feature_idx_

2

In [6]:
oner.prediction_dict_

{'total error': 16, 'rules (value: class)': {0: 0, 1: 1, 2: 1, 3: 2}}

In [15]:
y_predict=oner.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score
 
accuracy_score(y_test, y_predict)

0.8421052631578947

# RIPPER

In [17]:
from sklearn.model_selection import train_test_split


train,test = train_test_split(df, random_state=0)

In [18]:
import wittgenstein as lw
#creación del podelo RIPPER
ripper_clf = lw.RIPPER()
#entrenamiento del modelo
ripper_clf.fit(df, class_feat='target',pos_class=1) 
ripper_clf

/home/student10/.local/lib/python3.8/site-packages/wittgenstein/base.py:127: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  covered = covered.append(rule.covers(df))
/home/student10/.local/lib/python3.8/site-packages/wittgenstein/base.py:127: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  covered = covered.append(rule.covers(df))
/home/student10/.local/lib/python3.8/site-packages/wittgenstein/base.py:127: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  covered = covered.append(rule.covers(df))
/home/student10/.local/lib/python3.8/site-packages/wittgenstein/base.py:127: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  covered = covered.append(r

<RIPPER(max_rule_conds=None, n_discretize_bins=10, random_state=None, max_rules=None, max_total_conds=None, verbosity=0, k=2, dl_allowance=64, prune_size=0.33) with fit ruleset>

In [19]:
#reglas creadas por el modelo 
ripper_clf.out_model() 

[[thal=2 ^ ca=0] V
[slope=2 ^ cp=2 ^ restecg=1] V
[exang=0 ^ ca=0] V
[thal=2 ^ sex=0] V
[slope=2 ^ age=50.0-53.0 ^ restecg=0]]


In [20]:
X_test = test.drop('target', axis=1)
y_test = test['target']

In [21]:
#puntaje
ripper_clf.score(X_test,y_test)

/home/student10/.local/lib/python3.8/site-packages/wittgenstein/base.py:127: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  covered = covered.append(rule.covers(df))
/home/student10/.local/lib/python3.8/site-packages/wittgenstein/base.py:127: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  covered = covered.append(rule.covers(df))
/home/student10/.local/lib/python3.8/site-packages/wittgenstein/base.py:127: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  covered = covered.append(rule.covers(df))
/home/student10/.local/lib/python3.8/site-packages/wittgenstein/base.py:127: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  covered = covered.append(r

0.8421052631578947